---
- hosts: aws_ec2
  become: yes
  # roles:
  #   - role: es-role

  tasks:
    # tasks file for es-role
    - name: Add Elasticsearch apt key
      apt_key:
        url: "https://packages.elastic.co/GPG-KEY-elasticsearch"
        state: present
  

  # Installing APT repository
    - name: Install APT repository
      apt:
        name: apt-transport-https
        state: present


# Add the Elasticsearch apt repo. For versions 7 of the stack - use '7.x-prerelease':

    - name: Adding Elasticsearch repo
      apt_repository:
        repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main 
        state: present

    - name: Install Elasticsearch
      apt:
       name: elasticsearch
       update_cache: yes

   
# Update Elasticsearch config file to allow access (to secure Elasticsearch, bind to 'localhost'). 

    - name: Updating the config file to allow outside access
      lineinfile:
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: 'network.host:'
        line: 'network.host: 0.0.0.0'
 
# Update Elasticsearch port in config file 

    - name: Updating the port in config file 
      lineinfile:
       destfile: /etc/elasticsearch/elasticsearch.yml
       regexp: 'http.port:'
       line: 'http.port: 9200'

    ##   
    - name: Updating the liscence type in config file 
      lineinfile:
       destfile: /etc/elasticsearch/elasticsearch.yml
       regexp: 'xpack.license.self_generated.type:'
       line: 'xpack.license.self_generated.type: trial'   
 

 ##
    - name: Updating access in config file 
      lineinfile:
       destfile: /etc/elasticsearch/elasticsearch.yml
       regexp: 'xpack.security.enabled:'
       line: 'xpack.security.enabled: false'   
 

##
    - name: Updating the monitoring feature within Elasticsearch in config file 
      lineinfile:
       destfile: /etc/elasticsearch/elasticsearch.yml
       regexp: 'xpack.monitoring.collection.enabled:'
       line: 'xpack.monitoring.collection.enabled: true'   
 
# Update Elasticsearch nodes in config file

    - name: Updating the config file to allow outside access
      lineinfile:
        destfile: /etc/elasticsearch/elasticsearch.yml
        regexp: 'cluster.initial_master_nodes:'
        line: 'cluster.initial_master_nodes: ["{{ ansible_default_ipv4.address }}"]'

    
# Start Elasticsearch
    - name: Starting Elasticsearch
      service:
        name: elasticsearch
        state: started